/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Emp;

import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashish
 */
public class table extends javax.swing.JFrame {

    /**
     * Creates new form table
     */
    
    String[] head={"ISBN","Title","Publisher","Author","Category","Copies"};
    DefaultTableModel df=new DefaultTableModel(head,0);
    Connection cn;
    Statement st;
    
    public table() {
        initComponents();
        
        try{
        Class.forName("com.mysql.jdbc.Driver");
        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/classwork2","root","");
	st=cn.createStatement();
        ResultSet rs=st.executeQuery("select * from library1");
        
        while(rs.next())
                {
                    String[] row=new String[6];
                    
                    for(int i=1;i<=6;i++)
                    {
                        
                        row[i-1]=rs.getString(i);
                    }
                    df.addRow(row);
                    
                }
                
              jTable1.setModel(df);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(24);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText("jTextField1");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(jButton1)
                        .addGap(0, 294, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(374, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        Point point=evt.getPoint();
        int r=jTable1.rowAtPoint(point);
        
        details details=new details(Integer.parseInt(jTable1.getValueAt(r,0).toString()),jTable1.getValueAt(r,1).toString(),jTable1.getValueAt(r,2).toString(),jTable1.getValueAt(r,3).toString(),jTable1.getValueAt(r,4).toString(),Integer.parseInt(jTable1.getValueAt(r,5).toString()));
        details.setVisible(true);
        details.pack();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
         ResultSet rs2=null;
        
        if(getCount("title", jTextField1.getText())>0)
        {
            rs2=getRecord("title", jTextField1.getText());
        }
        else
        if(getCount("publisher", jTextField1.getText())>0)
        {
            rs2=getRecord("publisher", jTextField1.getText());
        }
        else
        if(getCount("author", jTextField1.getText())>0)
        {
            rs2=getRecord("author", jTextField1.getText());
        }
        else
        if(getCount("category", jTextField1.getText())>0)
        {
            rs2=getRecord("category", jTextField1.getText());
        }
            
        
        DefaultTableModel df1=new DefaultTableModel(head,0);
           
            while(rs2.next())
        
                {
                    String[] row=new String[6];
                    
                    for(int i=1;i<=6;i++)
                    {
                        
                        row[i-1]=rs2.getString(i);
                    }
                    df1.addRow(row);
                    
                }
            
        jTable1.setModel(df1);
            
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    
    int getCount(String fname,String value)
    {
        int x=0;
        try{
        ResultSet rs1= st.executeQuery("select count(*) from library1 where "+fname+" like '"+value+"'");
        if(rs1.next())
            x= rs1.getInt(1);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return x;
                
    }
    
    ResultSet getRecord(String fname,String value)
    {
        ResultSet rs2=null;
        try
        {
         rs2=st.executeQuery("select * from library1 where "+fname+" like '"+value+"'");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return rs2;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
